site/cards/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    url(r'^check$', views.check, name='check'),
    url(r'^rate$', views.rate, name='rate'),
    url(r'^finish$', views.finish, name='finish'),
    url(r'^all$', views.all, name='all'),
)

site/project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(pattern_name='cards:check')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cards/', include('cards.urls', namespace='cards')),
)

site/cards/models.py
from django.contrib.auth.models import User
from django.db import models


class Card(models.Model):
    def __unicode__(self):
        return self.content.front


class CardTag(models.Model):
    card = models.ForeignKey(Card)
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name


class CardContent(models.Model):
    card = models.OneToOneField(Card, related_name='content')
    front = models.TextField()
    back = models.TextField()
    author = models.ForeignKey(User, null=True, blank=True)

    def __unicode__(self):
        return self.front


class CardAnswer(models.Model):
    card = models.ForeignKey(Card, related_name='answers')
    answer = models.TextField(blank=True)
    start_time = models.TimeField(auto_now=True)
    end_time = models.TimeField(null=True)
    score = models.FloatField(null=True, default=0)

    def __unicode__(self):
        return '{} {}'.format(self.card.content.front, self.start_time)

site/cards/forms.py
from django import forms

from .models import CardAnswer


class CardAnswerForm(forms.ModelForm):
    id = forms.IntegerField(widget=forms.HiddenInput)

    class Meta:
        model = CardAnswer
        fields = ['id', 'answer']
        widgets = {
            'id': forms.HiddenInput(),
            'answer': forms.Textarea(attrs={'placeholder': 'Answer'}),
        }


class CardScoreForm(forms.ModelForm):
    id = forms.IntegerField(widget=forms.HiddenInput)

    class Meta:
        model = CardAnswer
        fields = ['id', 'score']
        widgets = {
            'id': forms.HiddenInput(),
            'score': forms.HiddenInput(),
        }

    def clean_score(self):
        score = self.cleaned_data['score']
        if score < 0.0 or score > 1.0:
            raise forms.ValidationError('Score is not in (0.0, 1.0) range.')
        return score

site/cards/views.py
from django.shortcuts import render, redirect
from django.utils import timezone

from .forms import CardAnswerForm, CardScoreForm
from .models import CardAnswer
from .utils import get_or_create_priority_card_answer, get_card_infos


def check(request):
    card_answer = get_or_create_priority_card_answer()
    form = CardAnswerForm(instance=card_answer)
    return render(request, 'cards/check.html', {
        'card': card_answer.card,
        'form': form,
    })


def rate(request):
    card_answer = CardAnswer.objects.get(pk=request.POST.get('id'))
    form = CardAnswerForm(request.POST, instance=card_answer)
    dict = {
        'card': card_answer.card,
        'form': form,
    }
    if not form.is_valid():
        return render(request, 'cards/check.html', dict)
    card_answer.end_time = timezone.now()
    form.save()
    dict['score_form'] = CardScoreForm(instance=card_answer)
    return render(request, 'cards/rate.html', dict)


def finish(request):
    card_answer = CardAnswer.objects.get(pk=request.POST.get('id'))
    score_form = CardScoreForm(request.POST, instance=card_answer)
    if not score_form.is_valid():
        return render(request, 'cards/rate.html', {
            'card': card_answer.card,
            'score_form': score_form,
        })
    return redirect('cards:check')


def all(request):
    return render(request, 'cards/all.html', {'card_infos': get_card_infos()})

site/cards/templates/cards/all.html
{% extends 'cards/base.html' %}
{% load card_faces %}

{% block content %}
  {% for card_info in card_infos %}
    {% card_full_info card_info %}
  {% endfor %}
{% endblock content %}

site/cards/templates/cards/base.html
<!doctype html>
{% load pipeline %}

<html lang='en'>
  <head>
    <title>Klios</title>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css' rel='stylesheet'>
    {% stylesheet 'main' %}
  </head>
  <body>
    <div class='content'>
      {% block content %}
      {% endblock content %}
    </div>
    <script src='//code.jquery.com/jquery-2.1.3.min.js'></script>
    <script src='//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js'></script>
    <script src='/static/js.js'></script>
  </body>
</html>

site/cards/templates/cards/card_back.html
<div class='card card-back panel panel-success'>
  <div class='panel-heading'>Correct answer</div>
  <div class='panel-body'>
    {{ card.content.back|safe }}
  </div>
</div>

site/cards/templates/cards/card_front.html
<div class='card card-front panel panel-default'>
  <div class='panel-body'>
    {{ card.content.front|safe }}
  </div>
</div>

site/cards/templates/cards/card_full_info.html
{% load card_faces %}

<div class='card card-full-info panel panel-default'>
  <div class='panel-heading'>Card: {{ card_info.card.pk }}</div>
  <div class='panel-body'>
    {% card_front card_info.card %}
    {% card_back card_info.card %}
    <div class='card panel panel-default'>
      <div class='panel-body'>
        <div class='row text-center'>
          <div class='col-sm-4'>
            Answers: {{ card_info.n_answers }}
          </div>
          <div class='col-sm-4'>
            Correct: {{ card_info.n_correct }}
          </div>
          <div class='col-sm-4'>
            Wrong: {{ card_info.n_wrong }}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

site/cards/templates/cards/check.html
{% extends 'cards/base.html' %}
{% load card_faces %}

{% block content %}
  {% card_front card %}

  <form action='{% url 'cards:rate' %}' method='post' id='check-form'>
    {% csrf_token %}
    {{ form.as_p }}
    <button class='btn btn-primary btn-block submit'>Submit</button>
  </form>
{% endblock content %}

site/cards/templates/cards/rate.html
{% extends 'cards/base.html' %}
{% load card_faces %}

{% block content %}
  {% card_front card %}
  {% card_back card %}

  {% if form.answer.value %}
    <div class='panel panel-default'>
      <div class='panel-heading'>Your answer</div>
      <div class='panel-body'>
        {{ form.answer.value }}
      </div>
    </div>
  {% endif %}

  <form action='{% url 'cards:finish' %}' method='post' id='rate-form'>
    {% csrf_token %}
    {{ score_form.as_p }}
      <div class='row'>
        <div class='col-sm-6'>
          <button type='button' class='incorrect btn btn-danger btn-block'>Incorrect</button>
        </div>
        <div class='col-sm-6'>
          <button type='button' class='correct btn btn-success btn-block'>Correct</button>
        </div>
      </div>
  </form>
{% endblock content %}